### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by prat0088** [jlao/ConsistentHashing#6]
I see ConsistentHashing's [license on NuGet is MIT](https://www.nuget.org/packages/ConsistentHashing/).  Does that extend to the source code in this repo?  From what I've read nobody will be able to use your code without specifying a license in GitHub, and your hash ring would be perfect for what I'm trying to do. 

The best summary I could find on GitHub and licenses:
- https://opensource.stackexchange.com/q/1720

**Comment by jlao** [comment]
Thanks for pointing this out. I've added a license file.
